### ISSUE TITLE
[X.x] I recommend this new feature for this package

### ISSUE THREAD

**Issue by aeq-dev** [ikechukwukalu/requirepin#1]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

Hi, thanks for this awesome package,
In fact, this is not a new feature but I'm wondering why you let the book object staff inside the package? if it's just an example of how to use it, I think the doc you wrote is enough, otherwise this may cause conflicts with existing book model or create a garbage table and classes :)
 

### Code sample

```php
Just remove book model, migration, ....etc
```

**Comment by ikechukwukalu** [comment]
Thanks @aeq-dev 

I'm a bit occupied right now, but I will implement your recommendation.

**Comment by ikechukwukalu** [comment]
@aeq-dev This has been removed in the latest version as of now.
